// lib/services/ffmpeg_service.dart
//
// Audio/Video mixing service — VoxCPM2 Khmer Neural Studio v4.0
//
// Strategy (ffmpeg_kit_flutter is discontinued/dead as of July 2026):
//   Phone generates TTS audio files locally via Edge TTS.
//   Server (PC with FFmpeg) handles mixing: duck original audio + overlay TTS.
//
// Two mixing modes:
//   1. SERVER mix  — uploads TTS files + segment metadata to PC server
//   2. LOCAL shell — uses the device's system FFmpeg binary if available
//      (Android usually doesn't have this, so server mode is default)

import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:http_parser/http_parser.dart';
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';

/// A single TTS segment to overlay on the video.
class DubbingSegment {
  final int     index;
  final double  startTime;
  final double  endTime;
  final String  gender;
  final String  text;
  final String? audioPath; // local MP3 path generated by Edge TTS

  const DubbingSegment({
    required this.index,
    required this.startTime,
    required this.endTime,
    required this.gender,
    required this.text,
    this.audioPath,
  });

  double get duration => endTime - startTime;
}

typedef FfmpegProgressCallback = void Function(String step, double progress);

class FfmpegService {

  // ── Server-based mixing (primary path) ────────────────────────────────────

  /// Upload the original video + all TTS MP3 segments to [serverUrl],
  /// ask the server to mix them with FFmpeg, then return the output video URL.
  ///
  /// The server receives:
  ///   • The video file (multipart)
  ///   • Each TTS audio file (multipart, named tts_0, tts_1, …)
  ///   • A JSON metadata field with segment timing / gender
  static Future<String> assembleDubbingViaServer({
    required String                videoPath,
    required List<DubbingSegment>  segments,
    required String                serverUrl,
    FfmpegProgressCallback?        onProgress,
  }) async {
    final valid = segments.where((s) => s.audioPath != null).toList();
    if (valid.isEmpty) throw Exception('No TTS audio files to mix.');

    onProgress?.call('📤 Uploading video + TTS to server...', 0.10);

    final uri = Uri.parse('$serverUrl/api/dubbing/assemble-tts-mix');
    final request = http.MultipartRequest('POST', uri);

    // Attach original video
    request.files.add(await http.MultipartFile.fromPath(
      'videoFile', videoPath,
      contentType: MediaType('video', 'mp4'),
    ));

    // Attach each TTS audio file
    for (int i = 0; i < valid.length; i++) {
      request.files.add(await http.MultipartFile.fromPath(
        'tts_$i', valid[i].audioPath!,
        contentType: MediaType('audio', 'mpeg'),
      ));
    }

    // Attach segment metadata
    final meta = valid.map((s) => {
      'index':      s.index,
      'start_time': s.startTime,
      'end_time':   s.endTime,
      'gender':     s.gender,
      'tts_key':    'tts_${valid.indexOf(s)}',
    }).toList();
    request.fields['segments'] = jsonEncode(meta);

    onProgress?.call('⏳ Server mixing (FFmpeg duck + overlay)...', 0.45);

    final streamed = await request.send().timeout(const Duration(minutes: 10));
    final res      = await http.Response.fromStream(streamed);

    if (res.statusCode != 200) {
      throw Exception('Server mix failed: HTTP ${res.statusCode}\n${res.body}');
    }

    final data = jsonDecode(res.body) as Map<String, dynamic>;
    if (data['success'] != true) {
      throw Exception(data['error'] ?? 'Server returned success=false');
    }

    onProgress?.call('✅ Mix complete!', 1.0);
    return '$serverUrl${data['videoUrl']}';
  }

  // ── Fallback: use /api/dubbing/assemble-custom (original server endpoint) ──

  /// Use the existing server endpoint that accepts pre-generated segment data.
  /// The server calls Edge TTS itself for any segment that needs audio.
  static Future<String> assembleDubbingViaCustomEndpoint({
    required String                      serverUrl,
    required String                      uploadedFilename,
    required List<Map<String, dynamic>>  segments,
    FfmpegProgressCallback?              onProgress,
  }) async {
    onProgress?.call('💻 Server: assembling dubbing...', 0.30);

    final res = await http.post(
      Uri.parse('$serverUrl/api/dubbing/assemble-custom'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'filename': uploadedFilename,
        'segments': segments,
      }),
    ).timeout(const Duration(minutes: 10));

    if (res.statusCode != 200) {
      throw Exception('assemble-custom failed: HTTP ${res.statusCode}');
    }

    final data = jsonDecode(res.body) as Map<String, dynamic>;
    if (data['success'] != true) {
      throw Exception(data['error'] ?? 'Server error');
    }

    onProgress?.call('✅ Done!', 1.0);
    return '$serverUrl${data['videoUrl']}';
  }

  // ── Utility: save bytes to temp file ──────────────────────────────────────

  static Future<String> saveBytesToTemp(List<int> bytes, String ext) async {
    final dir  = await getTemporaryDirectory();
    final path = '${dir.path}/${const Uuid().v4()}.$ext';
    await File(path).writeAsBytes(bytes);
    return path;
  }

  static void safeDelete(String path) {
    try { final f = File(path); if (f.existsSync()) f.deleteSync(); } catch (_) {}
  }
}
